### ISSUE TITLE
lib_lazcalc errors (divide by zero) when asking for zero inclination

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KSLib#77]
Line 32:

      set inc to ship:geoposition:lat*(desiredInc/abs(desiredInc)).

If desiredInc is 0, you'll have a divide-by-zero and the script crashes.

**Comment by TDW89** [comment]
:-( fixing it now.

**Comment by space-is-hard** [comment]
I think reverting to how 1.0 handled it would be best, unless you have a better idea

**Comment by TDW89** [comment]
If i remember correctly 1.0 handled it by setting the launch heading to 90 or 270, I had to handle it differently in order to use it in flight as if you start off at lat 45 and then it wont stay at 90 / 270 so went instead for setting the target inclination to + - your current lat.

**Comment by space-is-hard** [comment]
Ah yes I forgot about in-flight. How about this:

    IF ABS(SHIP:LATITUDE) > ABS(desiredInc) {
      IF desiredInc < 0 {
        SET inc TO SHIP:LATITUDE * -1.
      } ELSE {
        SET inc TO SHIP:LAITTUDE.
      }.
    //hudtext and all that jazz follows

**Comment by TDW89** [comment]
actually realized it should work without needing the sign, which just says do i want to ascend or descend from this point, as it has no option of ascending vs descending if its launching from above the inclination.
I am trying to fix it detecting retrograde orbits that are lower that the current lat.

**Comment by TDW89** [comment]
ok i think this https://github.com/TDW89/KSLib/commit/3b7b8a286705350d433df142f4ce923ab77d059d
still needs testing though, will probably install kerbinside and test it tomorrow.

**Comment by TDW89** [comment]
well it solves the `divide by 0` error but it highlights another issue. I may need to introduce some rounding to clean up the floating point errors, or look at another way of doing it.
It gives `Tried to push NaN to stack` when you go for a 0 inclination orbit (or any orbit that with an inclination lower than your launch lat) because it is trying to do `arcsin(1.0000000001)` or something similar :-(

**Comment by space-is-hard** [comment]
Maybe just clamp whatever value you think is floating too far with `max(min(...`

**Comment by TDW89** [comment]
thanks fixes it.
It also lets me fix another issue that i was thinking of opening as an enhancement for this script.
If you max(min( the arcsin function then you don't need to modify the target inclination. This should mean that you can launch into lower inclination orbits and it will attempt to correct in flight. (before if you launched from the ksc it would not let you launch into a 0 inclination orbit because you are not exactly on the equator and would change your target inclination to around 0.1)

**Comment by space-is-hard** [comment]
How aggressive would it be that way? Say if I launched from 10 degrees north latitude trying to get a zero degree inclination, would it have me head directly south and then turn ninety degrees east? Or is it more gradual?

**Comment by TDW89** [comment]
just going to check that but it probably wont be that noticeable it will just keep treating your current lat as the orbit inc until you get below the target inc, it is more likely to cause the issue of continuously burning west/ east than to launch N/S and try a 90 dec mid air turn.
